[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["chmod +x init_db.sh"]

[start]
cmd = "bash init_db.sh && uvicorn api.main:app --host 0.0.0.0 --port $PORT"
